### ISSUE TITLE
Customisable First app preview

### ISSUE THREAD

**Issue by tomaszpoliszuk** [MegaCookie/SwipyFolders#1]
Like in folder enhancer - possibility to change icon grid size (from 48 to full 60 or 30?).
Possibility to hide folder icon background - so we can have only grid or first app icon if chosen.

**Comment by JesseVelden** [comment]
Yup that would be a cool feature.

**Comment by JesseVelden** [comment]
With my latest commit I've made changes so you can set to hide the folder background and scale it up so it looks like a normal icon.  I'm considering making a separate tweak to customize the folder icon (including changing the icon grid size).
