### ISSUE TITLE
Add swipe down action

### ISSUE THREAD

**Issue by tomaszpoliszuk** [MegaCookie/SwipyFolders#2]

**Comment by JesseVelden** [comment]
I'm considering that feature, but that will cause issues with Spotlight when swiping down. Maybe in a future release.

**Comment by tomaszpoliszuk** [comment]
There are tweaks to prevent swiping down to spotlight (if i remember correctly one of them is Apex2)
Maybe also swipe left/right?

**Comment by JesseVelden** [comment]
It seems that adding

``` logos
 %new - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    otherGestureRecognizer.enabled = NO;
    return YES; 
}
```

on `SBIconView` will also allow swiping down on the icon, and disables Spotlight from showing up!
