### ISSUE TITLE
Quick action on other invoke methods (if possible)

### ISSUE THREAD

**Issue by tomaszpoliszuk** [MegaCookie/SwipyFolders#3]

**Comment by JesseVelden** [comment]
Please describe exactly what you mean, as I don't get it.

**Comment by tomaszpoliszuk** [comment]
For example:
Double Tap -> Quick action on first icon

**Comment by JesseVelden** [comment]
There are other apps for that such as [Forcy](https://github.com/StrayaDevTeam/Forcy)

**Comment by tomaszpoliszuk** [comment]
So we have forcy and invoke method in it is hold.
And if we would like to show Quick action on first icon it will work on hold?

**Comment by JesseVelden** [comment]
Alright I've fixed it! It will be present in the next update.
6c1398089843bcfb6846f5753552e3dce7159a08

**Comment by tomaszpoliszuk** [comment]
Thank you
