### ISSUE TITLE
Can't move a folder icon in editing mode

### ISSUE THREAD

**Issue by ettesion** [MegaCookie/SwipyFolders#5]
Hi, I started to like this tweak as I found this as an upgrade of TapTapFolder.

Is it possible to move a folder icon in editing mode without disabling the tweak and respringing?
I seem to be unable to move a folder icon by holding it a while.

Thanks for the great tweak!

**Comment by JesseVelden** [comment]
Yup, that is an issue I'm working on. Currently in v1.2.1-44 (not available on Cydia yet, but can be downloaded [here](https://www.dropbox.com/s/y9c2je6nq2qhfls/nl.jessevandervelden.swipyfolders_1.2.1-44_iphoneos-arm.deb?dl=1)):  you should be able to move folders, after you invoke editing mode on a normal icon. Can you report if that is working? Thanks!

**Comment by ettesion** [comment]
Yes, it fixed the problem.  Thanks!

**Comment by ettesion** [comment]
It might be a problem finding out which is a normal icon when you turn "Hide grey Folder Background" on, but in any case, even if you only see folder icons near your finger you can open one of them and then invoke editing mode on a normal icon inside.
