### ISSUE TITLE
Long-holding a folder icon invokes a short hold action 

### ISSUE THREAD

**Issue by ettesion** [MegaCookie/SwipyFolders#6]
I'd expect it to enter into editing mode, or to invoke a new action "long-hold" which is customizable, defaulted to "Edit icons".

**Comment by JesseVelden** [comment]
I think it's difficult to use a long hold gesture and a short hold gesture at the same time because they influence each other. So I don't think this problem can be solved, however I will change the behavior when the short hold method is set to 'nothing' to being able to move the folders.

**Comment by ettesion** [comment]
When I added a short-hold action to my fork of TapTapFolder, I trapped `iconTouchBegin` to record when a touch started and check it from `iconHandleLongPress`. (https://github.com/ettesion/TapTapFolder/commit/f0ed155e30277fd2167819cdb4d763ef9a3a3013)

I know your tweak adopts a different method to detect and handle events, so it may be fair to behave as you say.  Thanks for your consideration!

**Comment by JesseVelden** [comment]
That's interesting! So does it work without influencing the editing mode? It isn't really clear to me ;D

**Comment by ettesion** [comment]
Yes it does, and I actually meant `s/iconHandleLongPress/iconTapped/`.  `iconTouchBegin` sets `lastTouchedTime` to the time it is invoked, then a normap tap and a shold hold will both trigger `iconTapped` in which you can check the elapsed time since `lastTouchedTime` to see whether it was a tap or a short hold.  A long hold will be delegated to `iconHandleLongPress` without invoking `iconTapped`.

As SwipyFolder currently uses `UILongPressGestureRecognizer` so a short hold immediately fires a "long press", it may not be easy to detect a long hold without triggering a short hold action.  ;D

**Comment by JesseVelden** [comment]
Alright, finally had some time to implement it in the latest commit be7ca3b .
Thanks for the idea!
