### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by 4tified** [MegaCookie/SwipyFolders#7]
Hi! I was wondering if you would mind possibly sharing your headers with me? 
I'm actually using your source code specifically to learn how to make a preference bundle, and I'm coming across an error while compiling your tweak. Im guessing its something to do with the headers I'm using.

`==> Compiling SwipyFoldersPrefs.xm (armv7)…
SwipyFoldersPrefs.xm:132:69: error: property 'text' not found on object of type
      'id'
  ...NSString *appIndexText = alertController.textFields.firstObject.text;
                                                                     ^
1 error generated.
`

**Comment by JesseVelden** [comment]
Hmm strange that it happens there. I'm using iOS 9.3.3 SpringBoard headers in `$(THEOS)/include` and using the iOS 9.0 SDK for theos (with private frameworks). 
Also which fork of theos do you use? I'm compiling with https://github.com/theos/theos on my phone. You can also try `alertController.textFields[0].text`
or `((UITextField *)[alertController.textFields.firstObject]).text`

**Comment by 4tified** [comment]
Im using the same fork of theos as you are. However, I am using the iOS 8.1 SDK with iOS 9 headers.

In any case, the two methods you listed above didn't work for me for some reason.
However, I decided to break the original line into two chunks:

`UITextField *text_field = alertController.textFields.firstObject;`
`NSString *appIndexText = text_field.text;`

and it compiles just fine after that. 
Perhaps something to do with the way the updated SDK handles syntax?
In any case, thanks for the help and open sourcing this tweak! 
Im learning a lot just from looking through your code.

**Comment by JesseVelden** [comment]
Alright, I will fix this in a next commit. This is just my first tweak so not everything is the most efficient way, but have fun exploring and success with your own tweak development!
