### ISSUE TITLE
1.3.0: short-hold leaves app icon greyed out

### ISSUE THREAD

**Issue by ettesion** [MegaCookie/SwipyFolders#8]
First of all, thanks much for releasing this great tweak, and implementing a customizable short-hold action!

For me, version 1.4.x which had been there for awhile unfortunately didn't work at all, getting stuck in immediate crash into safe mode, but version 1.3.0 seems to be working well so far except for one relatively minor problem. (iPhone SE, iOS 9.3.3)

That is, I assign a shorthold action to launch second app in a folder, but invoking the action leaves the app icon greyed out when you get back to the home screen.

**Comment by JesseVelden** [comment]
You can try my new build: https://www.dropbox.com/s/9shxfr67n3lrqp2/nl.jessevandervelden.swipyfolders_1.4.1-99%2Bdebug_iphoneos-arm.deb?dl=1 

Or try compiling yourself

**Comment by ettesion** [comment]
Thanks, I installed it, but enabling the `Set first icon as Folder Preview` option all folder icons are now just grey rounded squares, as if they are all empty.

**Comment by ettesion** [comment]
Yet they still function, but no app icons are visible.

**Comment by JesseVelden** [comment]
As I made a lot of changes, and I added that to my latest commit: 917bdb1e4b6ce68b938a042babe5a53d99250765
Thanks for helping!

**Comment by JesseVelden** [comment]
You can try the new build on my repo: [megacookie.github.io](http://megacookie.github.io)
